server:
  port: 8120 #服务器端口号
spring:
  profiles:
    active: dev #环境设置
  application:
    name: service-oss #服务名
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI4G2ge2RvaS94QYDvRHQR
    keysecret: wKAcPxWfwqVl5N7nQlWFf1gpDBoATo
    bucketname: lilin-file-20210119
